import { readSchema, type SchemaEntry } from "../../core";

export interface PrepareSchemaEntriesResult {
  /** All schema entries read from generated schema artifact. */
  schemaEntries: SchemaEntry[];
  /** The first schema entry, treated as default config scope. */
  defaultEntry: SchemaEntry;
}

/**
 * Prepares generated schema and validates entry completeness.
 *
 * When `ids` is provided, every id must exist in generated schema entries.
 * The function throws a helpful error if schema is missing or incomplete.
 */
export async function prepareSchema(
  ids?: string[],
): Promise<PrepareSchemaEntriesResult> {
  // Read schema artifact generated by `intor generate`.
  const schema = await readSchema();

  // First entry is used as the default config key in `check`.
  const defaultEntry = schema.entries.at(0);
  if (!defaultEntry) {
    throw new Error(
      "No generated config schema found. Run `intor generate` first.",
    );
  }

  // If specific config ids are requested (in `validate`),
  // ensure all of them are represented in generated schema.
  if (ids && ids.length > 0) {
    const schemaIds = new Set(schema.entries.map((e) => e.id));
    const missingIds = ids.filter((id) => !schemaIds.has(id));
    if (missingIds.length > 0) {
      throw new Error(
        [
          "Generated schema is missing entries for the following config IDs:",
          ...missingIds.map((id) => `  - ${id}`),
          "",
          "Run `intor generate` first.",
        ].join("\n"),
      );
    }
  }

  return {
    schemaEntries: schema.entries,
    defaultEntry,
  };
}
